export const INVENTORY_ERROR_CODES = {
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_STOCK_ADJUSTMENT: 'INVALID_STOCK_ADJUSTMENT',
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  INVALID_RESERVATION: 'INVALID_RESERVATION',
  INVALID_RELEASE: 'INVALID_RELEASE',
  CONCURRENT_INVENTORY_UPDATE: 'CONCURRENT_INVENTORY_UPDATE',
} as const;

export type InventoryErrorCode = typeof INVENTORY_ERROR_CODES[keyof typeof INVENTORY_ERROR_CODES];
